dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.5.0
  cli:
    url: github.com/toitlang/pkg-cli
    version: ^1.2.0
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.9.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^2.3.0
